import { TrainingPartnerFormData } from './types';

export const emptyFormData: TrainingPartnerFormData = {
  applicationId: `TP-DRAFT-${Math.floor(100000 + Math.random() * 900000)}`,
  status: 'Draft',
  lastSaved: 'Not saved yet',

  // Step 01
  orgName: '',
  orgShortName: '',
  orgType: '',
  otherOrgType: '',
  yearOfEstablishment: '',
  officialWebsite: '',
  officialEmail: '',
  officialMobile: '',
  altMobile: '',
  registeredAddressLine1: '',
  registeredAddressLine2: '',
  state: 'Maharashtra',
  district: '',
  cityTown: '',
  blockTehsil: '',
  pinCode: '',
  headOfficeLat: '',
  headOfficeLng: '',

  // Step 02
  legalEntityType: '',
  registrationNumber: '',
  registrationDate: '',
  issuingAuthority: '',
  pan: '',
  gstin: '',
  cin: '',
  llpin: '',
  udyamNumber: '',
  darpanId: '',
  otherGovtReg: '',

  // Step 03
  repFullName: '',
  repDesignation: '',
  repDepartment: '',
  repEmail: '',
  repMobile: '',
  repAltNumber: '',
  repIdType: 'Aadhaar Card',
  repIdNumber: '',
  repIdDocName: undefined,
  isAuthorisedToRegister: '',
  authorisationLetterDoc: undefined,
  authorisationRefNumber: '',

  // Step 04
  centres: [],

  // Step 05
  maxTraineesPerBatch: 30,
  maxConcurrentTrainees: 150,
  avgBatchSize: 28,
  numberOfClassrooms: 4,
  batchesPerYear: 12,
  trainingHoursPerDay: 6,
  trainingDaysPerWeek: 6,
  operatingHours: '09:00 AM - 05:30 PM',
  trainingMode: 'Offline',
  operationalDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

  // Step 06
  classroomFacilities: ['Projector', 'Whiteboard', 'Computer Systems', 'Internet', 'CCTV', 'Seating Facility', 'Power Backup'],
  accessibilityFacilities: ['Wheelchair Accessible', 'Ramp', 'Accessible Toilet'],
  safetyFacilities: ['Fire Extinguishers', 'First Aid', 'Emergency Exit', 'Emergency Contact Display'],
  labs: [],

  // Step 07
  courses: [],

  // Step 08
  assessmentMethod: 'Combination',
  assessmentFrequency: 'Weekly formative + Final Summative',
  passingCriteriaPercentage: 60,
  isReassessmentAvailable: 'Yes',
  maxReassessmentAttempts: 2,
  assessmentAuthority: 'Sector Skill Council (SSC) & MSSDS',
  certificateIssuingAuthority: 'KAUSHAL / NCVET Joint Certification',
  certificateType: 'NSQF Aligned Skill Certificate',
  certificateValidityYears: 'Lifetime / 5 Years for Tech',
  isDigitalCertificateAvailable: 'Yes',
  certificateVerificationMethod: 'QR Code & DigiLocker API Integration',
  certificateTemplateName: 'kaushal_standard_cert_v2.pdf',

  // Step 09
  trainers: [],
  overallTrainerRatio: '1 : 30',
  practicalTrainerRatio: '1 : 15',

  // Step 10
  accreditations: [],
  recognitionName: '',
  recognitionAuthority: '',
  recognitionYear: '',

  // Step 11
  yearsOfExperience: 0,
  totalTraineesTrainedHistorically: 0,
  totalCoursesDelivered: 0,
  totalCentresOperated: 0,
  majorProgrammesSummary: '',
  historicalEnrolled: 0,
  historicalCompleted: 0,
  historicalCertified: 0,
  historicalPlaced: 0,
  historicalSelfEmployed: 0,
  historicalApprenticeship: 0,
  historicalCurrentlyEmployed: 0,
  historicalNoLongerEmployed: 0,

  // Step 12
  conductsPostTrainingFollowUp: 'Yes',
  followUpMethods: ['Phone', 'WhatsApp', 'Email'],
  followUpPeriod: '6 Months',
  avgMonthlySalary: 18500,
  retention3Month: 78,
  retention6Month: 72,
  retention12Month: 65,

  // Step 13
  hasEmployerPartnerships: 'Yes',
  employerPartnerships: [],
  employerPartners: [],
  hasDedicatedPlacementCell: 'Yes',
  placementOfficerName: '',
  placementOfficerContact: '',
  connectedEmployersCount: 0,
  jobOpportunitiesGeneratedLastYear: 0,
  placementDrivesConducted: 0,
  avgPlacementTimeDays: 45,

  // Step 14
  supportsSelfEmployment: 'Yes',
  selfEmploymentSupportTypes: ['Entrepreneurship Training', 'Finance / Loan Linkage', 'Government Scheme Linkage'],
  selfEmploymentDetails: '',
  facilitatesApprenticeships: 'Yes',
  apprenticeshipSectors: 'Automotive, Electrical, Capital Goods',
  apprenticeshipStipendRange: '₹9,500 - ₹14,500 / month',
  apprenticeshipsCount: 0,
  apprenticeshipConversionRate: '78%',

  // Step 15
  maintainsDigitalTraineeRecords: 'Yes',
  existingMisErpName: 'KAUSHAL SkillIMS Enterprise v3.2',
  hasApiAvailable: 'Yes',
  apiType: 'REST API / JSON (OAS 3.0)',
  integrationContact: 'tech-desk@abctraining.org',
  hasBulkUploadCapability: 'Yes',
  hasDigitalAttendance: 'Yes',
  hasDigitalAssessment: 'Yes',
  internetAvailability: 'Reliable',

  // Step 16
  hasGovtProgrammeAssociation: 'Yes',
  govtProgrammes: [],
  associatedGovtSchemes: ['PMKVY (Pradhan Mantri Kaushal Vikas Yojana)', 'MSSDS (Maharashtra State Skill Development Society)'],

  // Step 17
  accountHolderName: '',
  bankName: '',
  branch: '',
  branchName: '',
  accountNumber: '',
  confirmAccountNumber: '',
  ifsc: '',
  ifscCode: '',
  accountType: 'Current',
  cancelledChequeDocName: undefined,
  turnoverYear1: 185,
  turnoverYear2: 240,
  turnoverYear3: 310,
  netWorth: 125,

  // Step 18
  documents: [
    { id: 'd1', documentType: 'Organisation Registration Certificate', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd2', documentType: 'PAN Card of Organisation', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd3', documentType: 'GST Registration Certificate', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd4', documentType: 'Authorisation Letter for Representative', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd5', documentType: 'Registered Office Address Proof', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd6', documentType: 'Bank Cancelled Cheque / Bank Statement', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd7', documentType: 'Accreditation / Affiliation Certificate', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: false },
    { id: 'd8', documentType: 'Training Centre Premises Proof & Layout', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: true },
    { id: 'd9', documentType: 'Fire Safety & Building NOC', documentNumber: '', fileName: '', fileSizeMb: 0, status: 'Uploaded', isMandatory: false },
  ],

  // Step 19
  confirmAccurate: false,
  confirmAuthority: false,
  confirmGenuineDocs: false,
  agreeGovtVerification: false,
  agreeMaintainRecords: false,
  agreeReportOutcomes: false,
  agreeUpdateInfo: false,
  agreePrivacyData: false,
  agreeRevocationTerms: false,
  dataProcessingConsent: false,
  consentDeclarationAccurate: false,
  consentGuidelinesAdherence: false,
  consentFeeRules: false,
  consentPremisesInspection: false,
  consentBiometricAttendance: false,
  consentNotBlacklisted: false,
  digitalSignatureName: '',
  digitalSignatureDesignation: '',
  placeOfDeclaration: '',

  auditLogs: [
    {
      id: 'log-1',
      user: 'System Admin',
      role: 'System Initialization',
      action: 'Registration Draft Session Created',
      timestamp: '16 Sep 2026, 11:20 AM',
      newValue: 'Draft Started',
      reason: 'User initialized KAUSHAL Training Partner Registration',
      ipAddress: '103.112.44.18 (Maharashtra State Network)',
    },
  ],

  corrections: [
    {
      id: 'cor-1',
      field: 'Registered Office Address Proof',
      currentValue: 'rent_agreement_expired_2024.pdf',
      reviewerComment: 'Address proof electricity bill or lease deed submitted is older than 6 months. Please upload latest notarised lease or 2026 utility bill.',
      correctionType: 'document',
      status: 'Pending Action',
    },
    {
      id: 'cor-2',
      field: 'Course 02: CNC Operator Syllabus',
      currentValue: 'v1_syllabus_incomplete.pdf',
      reviewerComment: 'Module 4 practical safety hours do not meet NSQF Level 4 mandate of 90 practical lab hours. Please upload updated module breakdown.',
      correctionType: 'document',
      status: 'Pending Action',
    },
    {
      id: 'cor-3',
      field: 'Trainer 02 Qualification Proof',
      currentValue: 'marksheets_missing.pdf',
      reviewerComment: 'Degree certificate missing; only 10th marksheet uploaded for Trainer Rajesh Deshmukh. Please attach degree & TOT certificate.',
      correctionType: 'document',
      status: 'Pending Action',
    },
  ],
};

export const demoFilledFormData: TrainingPartnerFormData = {
  ...emptyFormData,
  applicationId: 'TP-MH-2026-000184',
  status: 'Draft',
  lastSaved: 'Just now (Auto-saved)',

  // Step 01
  orgName: 'ABC Skill Development & Vocational Institute Pvt Ltd',
  orgShortName: 'ABC Skills',
  orgType: 'Private Training Provider',
  yearOfEstablishment: '2016',
  officialWebsite: 'https://www.abcskills.org.in',
  officialEmail: 'info@abcskills.org.in',
  officialMobile: '9822019482',
  altMobile: '020-25674821',
  registeredAddressLine1: 'Plot No. 44/B, Shivajinagar Tech Park',
  registeredAddressLine2: 'Opposite State Bank, Off F.C. Road',
  state: 'Maharashtra',
  district: 'Pune',
  cityTown: 'Pune',
  blockTehsil: 'Haveli',
  pinCode: '411005',
  headOfficeLat: '18.5204',
  headOfficeLng: '73.8567',

  // Step 02
  legalEntityType: 'Private Limited Company',
  registrationNumber: 'ROC-PUN-309182',
  registrationDate: '2016-04-12',
  issuingAuthority: 'Registrar of Companies, Pune (Ministry of Corporate Affairs)',
  pan: 'AAACM4821K',
  gstin: '27AAACM4821K1ZX',
  cin: 'U80902MH2016PTC309182',
  udyamNumber: 'UDYAM-MH-26-0084920',
  darpanId: '',
  otherGovtReg: 'MSSDS Empanelled TP ID: MSSDS/TP/2019/148',

  // Step 03
  repFullName: 'Suhas Manohar Kulkarni',
  repDesignation: 'Managing Director & CEO',
  repDepartment: 'Executive Leadership',
  repEmail: 'suhas.kulkarni@abcskills.org.in',
  repMobile: '9822019482',
  repAltNumber: '9422038190',
  repIdType: 'Aadhaar Card',
  repIdNumber: 'XXXX-XXXX-8421',
  repIdDocName: 'suhas_kulkarni_aadhaar_verified.pdf',
  isAuthorisedToRegister: 'Yes',
  authorisationLetterDoc: 'board_resolution_authorisation_letter_2026.pdf',
  authorisationRefNumber: 'ABC/BOD/RES/2026/08',

  // Step 04
  centres: [
    {
      id: 'c1',
      centreName: 'ABC Regional Centre of Skill Excellence - Pune',
      centreCode: 'ABC-PUN-01',
      centreType: 'Permanent',
      addressLine1: 'Gate 3, MIDC Industrial Area, Bhosari',
      state: 'Maharashtra',
      district: 'Pune',
      city: 'Pimpri-Chinchwad',
      tehsil: 'Haveli',
      pinCode: '411026',
      latitude: '18.6298',
      longitude: '73.8131',
      managerName: 'Anjali R. Deshpande',
      managerDesignation: 'Centre Head',
      managerMobile: '9823194820',
      managerEmail: 'pune.centre@abcskills.org.in',
      operationalStatus: 'Active',
      maxTraineesPerBatch: 30,
      maxConcurrentTrainees: 180,
      classroomsCount: 6,
      verificationStatus: 'Verified',
    },
    {
      id: 'c2',
      centreName: 'ABC Advanced Technical Training Centre - Mumbai Suburban',
      centreCode: 'ABC-MUM-02',
      centreType: 'Permanent',
      addressLine1: 'B-Block, Andheri Industrial Estate, Veera Desai Road',
      state: 'Maharashtra',
      district: 'Mumbai Suburban',
      city: 'Andheri West',
      tehsil: 'Andheri',
      pinCode: '400053',
      latitude: '19.1363',
      longitude: '72.8277',
      managerName: 'Vikramjit Singh',
      managerDesignation: 'Centre Director',
      managerMobile: '9819204910',
      managerEmail: 'mumbai.centre@abcskills.org.in',
      operationalStatus: 'Active',
      maxTraineesPerBatch: 30,
      maxConcurrentTrainees: 120,
      classroomsCount: 4,
      verificationStatus: 'Verified',
    },
    {
      id: 'c3',
      centreName: 'ABC Vidarbha Rural & Industrial Skilling Centre - Nagpur',
      centreCode: 'ABC-NAG-03',
      centreType: 'Permanent',
      addressLine1: 'Plot 12, Hingna MIDC, Near Electronics Zone',
      state: 'Maharashtra',
      district: 'Nagpur',
      city: 'Nagpur',
      tehsil: 'Hingna',
      pinCode: '440028',
      latitude: '21.0967',
      longitude: '78.9953',
      managerName: 'Pravin M. Raut',
      managerDesignation: 'Senior Training Manager',
      managerMobile: '9422184920',
      managerEmail: 'nagpur.centre@abcskills.org.in',
      operationalStatus: 'Active',
      maxTraineesPerBatch: 30,
      maxConcurrentTrainees: 120,
      classroomsCount: 4,
      verificationStatus: 'Verified',
    },
  ],

  // Step 05
  maxTraineesPerBatch: 30,
  maxConcurrentTrainees: 420,
  avgBatchSize: 28,
  numberOfClassrooms: 14,
  batchesPerYear: 36,
  trainingHoursPerDay: 7,
  trainingDaysPerWeek: 6,
  operatingHours: '08:30 AM - 05:30 PM',
  trainingMode: 'Hybrid',
  operationalDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],

  // Step 06
  classroomFacilities: [
    'Projector',
    'Smart Board',
    'Whiteboard',
    'Computer Systems',
    'Internet',
    'CCTV',
    'Air Conditioning',
    'Seating Facility',
    'Power Backup',
  ],
  accessibilityFacilities: [
    'Wheelchair Accessible',
    'Accessible Toilet',
    'Ramp',
    'Lift',
    'Accessible Entrance',
    'Assistive Facilities',
  ],
  safetyFacilities: [
    'Fire Extinguishers',
    'Fire Safety System',
    'First Aid',
    'Emergency Exit',
    'Emergency Contact Display',
  ],
  labs: [
    {
      id: 'l1',
      labName: 'Electric Vehicle & Battery Diagnostic Lab',
      labType: 'EV Lab',
      capacity: 30,
      workstations: 25,
      equipmentList: [
        { name: 'EV Chassis Diagnostic Rig', quantity: 4, condition: 'Operational', lastMaintenanceDate: '2026-08-10' },
        { name: 'Li-Ion Battery Cell Balancer & BMS Analyzer', quantity: 8, condition: 'Operational', lastMaintenanceDate: '2026-07-22' },
        { name: 'High-Voltage Insulation Multimeter Kit', quantity: 15, condition: 'Operational', lastMaintenanceDate: '2026-08-01' },
      ],
    },
    {
      id: 'l2',
      labName: 'Advanced CNC Machining & Automation Lab',
      labType: 'Manufacturing Lab',
      capacity: 30,
      workstations: 20,
      equipmentList: [
        { name: 'Siemens 828D CNC Turning Center', quantity: 2, condition: 'Operational', lastMaintenanceDate: '2026-08-14' },
        { name: 'Fanuc 3-Axis VMC Milling Machine', quantity: 2, condition: 'Operational', lastMaintenanceDate: '2026-08-15' },
        { name: 'CAM Simulator PC Workstations', quantity: 25, condition: 'Operational', lastMaintenanceDate: '2026-08-20' },
      ],
    },
    {
      id: 'l3',
      labName: 'Solar PV & Renewable Energy Simulator Lab',
      labType: 'Solar Lab',
      capacity: 30,
      workstations: 24,
      equipmentList: [
        { name: 'Solar PV Test Bench with Inverter Sync', quantity: 6, condition: 'Operational', lastMaintenanceDate: '2026-07-15' },
        { name: 'Solar Irradiance Metres & Pyranometers', quantity: 12, condition: 'Operational', lastMaintenanceDate: '2026-06-30' },
      ],
    },
  ],

  // Step 07
  courses: [
    {
      id: 'crs-1',
      courseName: 'Electric Vehicle Service & BMS Specialist',
      courseCode: 'EV-AUTO-L4-01',
      sector: 'Automotive & Clean Mobility',
      subSector: 'Electric Vehicles',
      jobRole: 'EV Service Technician (NSQF Level 4)',
      courseCategory: 'Short-Term',
      durationHours: 360,
      trainingMode: 'Hybrid',
      qualificationRequired: '10th / 12th Pass or ITI Electrical/Motor Mechanic',
      minAge: 18,
      maxAge: 32,
      targetBeneficiaryGroup: 'Youth, ITI Graduates, Displaced Petrol/Diesel Mechanics',
      learningObjectives: 'To equip trainees with deep diagnostic skills for EV powertrains, battery thermal management, and high-voltage safety.',
      learningOutcomes: 'Independently inspect, diagnose and repair EV battery modules, power electronic inverters, and onboard charger subsystems.',
      skillsCovered: ['BMS Diagnostics', 'High-Voltage Safety SOPs', 'CAN-Bus Telemetry', 'Battery Cell Testing'],
      modules: [
        { id: 'm1', moduleNumber: 1, moduleTitle: 'High Voltage Safety & EV Architecture', durationHours: 60, description: 'Foundations of EV battery safety protocols and PPE', skillsCovered: ['Safety PPE', 'Arc-Flash Protocols'] },
        { id: 'm2', moduleNumber: 2, moduleTitle: 'Lithium Battery Chemistry & Cell Balancing', durationHours: 100, description: 'Deep dive into chemistry, thermal runaway prevention, and cell sorting', skillsCovered: ['Battery Chemistry', 'BMS Calibration'] },
        { id: 'm3', moduleNumber: 3, moduleTitle: 'Motor Controller & Inverter Diagnosis', durationHours: 100, description: 'BLDC and PMSM motor diagnostics and regenerative braking tuning', skillsCovered: ['Motor Diagnostics', 'Inverter Calibration'] },
        { id: 'm4', moduleNumber: 4, moduleTitle: 'Field Apprenticeship & Vehicle Troubleshooting', durationHours: 100, description: 'Real vehicle test bed repairs with authorized EV OEM service centres', skillsCovered: ['On-vehicle diagnostics', 'Customer Handover'] },
      ],
      assessmentMethod: 'Practical (60%) + Theory (40%) with SSC Automotive',
      passingCriteria: 'Minimum 60% in Practical and 50% in Theory',
      certificateIssuingAuthority: 'Automotive Skills Development Council (ASDC) & KAUSHAL',
    },
    {
      id: 'crs-2',
      courseName: 'CNC Machine Operator & Precision Machining',
      courseCode: 'MFG-CNC-L4-02',
      sector: 'Capital Goods & Manufacturing',
      subSector: 'Machine Tools',
      jobRole: 'CNC Turning & Milling Specialist',
      courseCategory: 'Short-Term',
      durationHours: 320,
      trainingMode: 'Offline',
      qualificationRequired: '10th Pass or ITI Turner/Machinist',
      minAge: 18,
      maxAge: 30,
      targetBeneficiaryGroup: 'Industrial ITI graduates, Rural youth seeking factory employment',
      learningObjectives: 'Operate standard CNC lathe and milling centres, verify precision dimensional tolerances using micrometer and CMM.',
      learningOutcomes: 'Produce engineering metal parts conforming to DIN/ISO tolerances within ±0.01 mm.',
      skillsCovered: ['G & M Code Programming', 'Tool Offset Setting', 'Metrology & CMM', 'Workholding'],
      modules: [
        { id: 'm21', moduleNumber: 1, moduleTitle: 'Engineering Drawings & GD&T Standards', durationHours: 60, description: 'Reading blueprints, tolerance symbols, and manufacturing standards', skillsCovered: ['Blueprint Reading', 'GD&T'] },
        { id: 'm22', moduleNumber: 2, moduleTitle: 'CNC Lathe Setup & Programming', durationHours: 130, description: 'Hands-on tool setting, zero offset, and cycle programming', skillsCovered: ['CNC Turning', 'G-Codes'] },
        { id: 'm23', moduleNumber: 3, moduleTitle: 'Quality Inspection & Industry Production Run', durationHours: 130, description: 'Batch production with live MIDC automotive component vendors', skillsCovered: ['Quality Control', 'Tool Wear Monitoring'] },
      ],
      assessmentMethod: 'Direct Machining Test (70%) + SSC Viva (30%)',
      passingCriteria: 'Zero-scrap component tolerance in final exam',
      certificateIssuingAuthority: 'Capital Goods Skill Council (CGSC) & MSSDS',
    },
  ],

  // Step 08
  assessmentMethod: 'Combination (Practical + Written + Industry Evaluator)',
  assessmentFrequency: 'Weekly formative assessments + Mid-term + Final Summative Examination',
  passingCriteriaPercentage: 65,
  isReassessmentAvailable: 'Yes',
  maxReassessmentAttempts: 2,
  assessmentAuthority: 'Sector Skill Council (SSC) & MSSDS Quality Directorate',
  certificateIssuingAuthority: 'Government of Maharashtra / KAUSHAL Joint Portal',
  certificateType: 'NSQF Government Verified Digital Skill Certificate',
  certificateValidityYears: 'Lifetime Verification on Blockchain / DigiLocker',
  isDigitalCertificateAvailable: 'Yes',
  certificateVerificationMethod: 'Instant QR Code Scan & DigiLocker Verifiable Credential',
  certificateTemplateName: 'maharashtra_kaushal_qr_cert_standard.pdf',

  // Step 09
  trainers: [
    {
      id: 'tr-1',
      fullName: 'Ganesh Shrikant Patil',
      trainerId: 'TR-AUTO-MH-0841',
      email: 'ganesh.patil@abcskills.org.in',
      mobile: '9822148291',
      highestQualification: 'B.E. Automobile Engineering',
      specialisation: 'Electric Vehicle Powertrain & Battery Systems',
      yearsOfExperience: 9,
      industryExperienceYears: 6,
      teachingExperienceYears: 3,
      coursesAssigned: ['Electric Vehicle Service & BMS Specialist'],
      trainerCertification: 'ASDC Certified Master Trainer (TOT/2023/8492)',
      accreditationId: 'ASDC-TOT-MH-841',
      status: 'Active',
      resumeName: 'ganesh_patil_cv_tot_certified.pdf',
    },
    {
      id: 'tr-2',
      fullName: 'Rajesh Vitthal Deshmukh',
      trainerId: 'TR-MFG-MH-1092',
      email: 'rajesh.deshmukh@abcskills.org.in',
      mobile: '9823019482',
      highestQualification: 'B.E. Mechanical Engineering',
      specialisation: 'CNC Programming & Multi-Axis Machining',
      yearsOfExperience: 12,
      industryExperienceYears: 8,
      teachingExperienceYears: 4,
      coursesAssigned: ['CNC Machine Operator & Precision Machining'],
      trainerCertification: 'CGSC Certified Master Trainer (TOT/2022/9102)',
      accreditationId: 'CGSC-TOT-MH-1092',
      status: 'Active',
      resumeName: 'rajesh_deshmukh_cv_mechanical.pdf',
    },
    {
      id: 'tr-3',
      fullName: 'Snehal Ajay Kulkarni',
      trainerId: 'TR-ELE-MH-3341',
      email: 'snehal.kulkarni@abcskills.org.in',
      mobile: '9764129840',
      highestQualification: 'M.Tech Electronics & Power Systems',
      specialisation: 'Solar Inverters & Smart Grid Micro-controllers',
      yearsOfExperience: 7,
      industryExperienceYears: 4,
      teachingExperienceYears: 3,
      coursesAssigned: ['Solar PV & Renewable Energy Technician'],
      trainerCertification: 'SCJPS Certified Trainer (TOT/2024/1102)',
      accreditationId: 'SCJPS-TOT-MH-3341',
      status: 'Active',
      resumeName: 'snehal_kulkarni_mtech_tot.pdf',
    },
  ],
  overallTrainerRatio: '1 Trainer : 28 Trainees',
  practicalTrainerRatio: '1 Practical Trainer : 14 Trainees',

  // Step 10
  accreditations: [
    {
      id: 'acc-1',
      body: 'National Council for Vocational Education and Training (NCVET)',
      name: 'Recognised Awarding Body / Training Provider Affiliation',
      number: 'NCVET/AB/MH/2022/0149',
      issueDate: '2022-07-01',
      expiryDate: '2027-06-30',
      status: 'Active',
      certificateFile: 'ncvet_affiliation_order_2022_2027.pdf',
    },
    {
      id: 'acc-2',
      body: 'Maharashtra State Skill Development Society (MSSDS)',
      name: 'Pramod Mahajan Kaushalya Udyojakata Abhiyan Empanelment',
      number: 'MSSDS/TP/PUN/2021/88',
      issueDate: '2021-09-15',
      expiryDate: '2026-09-14',
      status: 'Under Renewal',
      certificateFile: 'mssds_empanelment_letter_pune.pdf',
    },
  ],
  recognitionName: 'Best Technical Skill Centre in Western Maharashtra (Industry Linkage Award)',
  recognitionAuthority: 'Directorate of Vocational Education and Training (DVET), Maharashtra',
  recognitionYear: '2024',

  // Step 11
  yearsOfExperience: 10,
  totalTraineesTrainedHistorically: 5420,
  totalCoursesDelivered: 18,
  totalCentresOperated: 3,
  majorProgrammesSummary: 'Delivered PMKVY 3.0 & 4.0, MSSDS Chief Minister Maha-Kaushalya, and Tata Motors CSR EV Skilling across Pune, Thane and Nagpur.',
  historicalEnrolled: 5420,
  historicalCompleted: 5040,
  historicalCertified: 4680,
  historicalPlaced: 3720,
  historicalSelfEmployed: 420,
  historicalApprenticeship: 560,
  historicalCurrentlyEmployed: 3940,
  historicalNoLongerEmployed: 200,

  // Step 12
  conductsPostTrainingFollowUp: 'Yes',
  followUpMethods: ['Phone', 'WhatsApp', 'Email', 'In-Person', 'Alumni Portal'],
  followUpPeriod: '12 Months',
  avgMonthlySalary: 21500,
  retention3Month: 82,
  retention6Month: 76,
  retention12Month: 71,

  // Step 13
  hasEmployerPartnerships: 'Yes',
  employerPartnerships: [
    { id: 'ep-1', employerName: 'Tata Motors Limited', industry: 'Automotive & EV Manufacturing', partnershipType: 'Hiring Partnership', agreementType: 'Formal MoU', startDate: '2022-01-10', endDate: '2027-01-09', documentName: 'tata_motors_mou_hiring.pdf' },
    { id: 'ep-2', employerName: 'Mahindra & Mahindra Ltd', industry: 'Automotive & Heavy Equipment', partnershipType: 'Placement', agreementType: 'MoU & Apprenticeship Tie-up', startDate: '2021-08-01', endDate: '2026-07-31', documentName: 'mahindra_apprentice_mou.pdf' },
    { id: 'ep-3', employerName: 'Bharat Forge Ltd', industry: 'Forging & Precision Machining', partnershipType: 'Curriculum Support', agreementType: 'Industry Advisory Board MoU', startDate: '2023-03-15', endDate: '2028-03-14', documentName: 'bharat_forge_mou.pdf' },
    { id: 'ep-4', employerName: 'Thermax Limited', industry: 'Energy & Environmental Engineering', partnershipType: 'Apprenticeship', agreementType: 'NAPS Registered Agreement', startDate: '2022-11-01', endDate: '2025-10-31', documentName: 'thermax_naps_mou.pdf' },
    { id: 'ep-5', employerName: 'Larsen & Toubro (L&T Heavy Engineering)', industry: 'Industrial Manufacturing', partnershipType: 'Placement', agreementType: 'Campus Hiring Agreement', startDate: '2023-05-01', endDate: '2026-04-30', documentName: 'lt_campus_hiring_agreement.pdf' },
  ],
  hasDedicatedPlacementCell: 'Yes',
  placementOfficerName: 'Rameshwar B. Kadam',
  placementOfficerContact: '9822491024 / placement@abcskills.org.in',
  connectedEmployersCount: 48,
  jobOpportunitiesGeneratedLastYear: 1420,
  placementDrivesConducted: 14,
  avgPlacementTimeDays: 38,

  // Step 14
  supportsSelfEmployment: 'Yes',
  selfEmploymentSupportTypes: [
    'Entrepreneurship Training',
    'Business Mentoring',
    'Finance / Loan Linkage',
    'Incubation',
    'Market Linkage',
    'Government Scheme Linkage',
  ],
  selfEmploymentDetails: 'Partnered with Bank of Maharashtra and PMEGP/Mudra nodal branch in Pune to facilitate collateral-free equipment financing for EV diagnostic garage startups.',
  facilitatesApprenticeships: 'Yes',
  apprenticeshipSectors: 'Automotive, Manufacturing, Clean Energy, Industrial Electrical',
  apprenticeshipStipendRange: '₹10,500 - ₹15,000 / month (NAPS Compliant)',
  apprenticeshipsCount: 560,
  apprenticeshipConversionRate: '82% of apprentices absorbed into permanent payroll',

  // Step 15
  maintainsDigitalTraineeRecords: 'Yes',
  existingMisErpName: 'ABC-EduTrack Enterprise LMS & BioMetric Attendance System',
  hasApiAvailable: 'Yes',
  apiType: 'REST API / JSON (OAS 3.0 Compliant with KAUSHAL Webhook Spec)',
  integrationContact: 'api-gateway@abcskills.org.in',
  hasBulkUploadCapability: 'Yes',
  hasDigitalAttendance: 'Yes',
  hasDigitalAssessment: 'Yes',
  internetAvailability: 'Reliable',

  // Step 16
  hasGovtProgrammeAssociation: 'Yes',
  govtProgrammes: [
    {
      id: 'gp-1',
      programmeName: 'Pramod Mahajan Kaushalya Udyojakata Vikas Abhiyan (PMKUVA)',
      department: 'Skill Development & Entrepreneurship Department, Govt of Maharashtra',
      schemeCode: 'MH-PMKUVA-2022',
      approvalNumber: 'MSSDS/SANCTION/PUN/2022/419',
      startDate: '2022-04-01',
      endDate: '2026-03-31',
      status: 'Active',
    },
    {
      id: 'gp-2',
      programmeName: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0 Special Projects)',
      department: 'Ministry of Skill Development & Entrepreneurship (MSDE), Govt of India',
      schemeCode: 'MSDE-PMKVY-SP-08',
      approvalNumber: 'NSDC/PMKVY4/MH/SP/8491',
      startDate: '2023-10-01',
      endDate: '2025-09-30',
      status: 'Active',
    },
  ],

  // Step 17
  accountHolderName: 'ABC Skill Development & Vocational Institute Private Limited',
  bankName: 'State Bank of India',
  branch: 'Shivajinagar SME Commercial Branch, Pune',
  accountNumber: '40918234821',
  ifsc: 'SBIN0000455',
  accountType: 'Current',
  cancelledChequeDocName: 'sbi_current_account_cancelled_cheque_2026.pdf',

  // Step 18
  documents: [
    { id: 'd1', documentType: 'Organisation Registration Certificate (Certificate of Incorporation)', documentNumber: 'ROC-PUN-309182', issueDate: '2016-04-12', issuingAuthority: 'MCA', fileName: 'mca_certificate_of_incorporation.pdf', fileSizeMb: 1.8, status: 'Uploaded', isMandatory: true },
    { id: 'd2', documentType: 'PAN Card of Organisation', documentNumber: 'AAACM4821K', issueDate: '2016-05-10', issuingAuthority: 'Income Tax Dept', fileName: 'pan_card_abc_skills.pdf', fileSizeMb: 0.9, status: 'Uploaded', isMandatory: true },
    { id: 'd3', documentType: 'GST Registration Certificate (GST REG-06)', documentNumber: '27AAACM4821K1ZX', issueDate: '2017-07-01', issuingAuthority: 'GSTN', fileName: 'gst_certificate_reg06.pdf', fileSizeMb: 1.2, status: 'Uploaded', isMandatory: true },
    { id: 'd4', documentType: 'Board Resolution & Authorisation Letter', documentNumber: 'ABC/BOD/RES/2026/08', issueDate: '2026-08-01', issuingAuthority: 'Board of Directors', fileName: 'board_authorisation_letter_suhas.pdf', fileSizeMb: 1.4, status: 'Uploaded', isMandatory: true },
    { id: 'd5', documentType: 'Registered Office Address Proof (Lease Deed & Utility Bill)', documentNumber: 'PUN/SUB-REG/2024/9182', issueDate: '2024-03-01', expiryDate: '2029-02-28', issuingAuthority: 'Sub-Registrar Haveli', fileName: 'registered_office_registered_lease.pdf', fileSizeMb: 3.4, status: 'Uploaded', isMandatory: true },
    { id: 'd6', documentType: 'Bank Cancelled Cheque & Mandate Form', documentNumber: 'CHQ-849102', issueDate: '2026-08-20', issuingAuthority: 'State Bank of India', fileName: 'sbi_cancelled_cheque_stamped.pdf', fileSizeMb: 0.8, status: 'Uploaded', isMandatory: true },
    { id: 'd7', documentType: 'Accreditation / Affiliation Certificate (NCVET)', documentNumber: 'NCVET/AB/MH/2022/0149', issueDate: '2022-07-01', expiryDate: '2027-06-30', issuingAuthority: 'NCVET', fileName: 'ncvet_accreditation_order.pdf', fileSizeMb: 2.1, status: 'Uploaded', isMandatory: false },
    { id: 'd8', documentType: 'Training Centre Premises Proof & Floor Layout Blueprint', documentNumber: 'MIDC/BHO/ALLOT/2019/41', issueDate: '2019-11-10', issuingAuthority: 'MIDC Pune', fileName: 'centre_layout_blueprint_bhosari.pdf', fileSizeMb: 4.8, status: 'Uploaded', isMandatory: true },
    { id: 'd9', documentType: 'Fire Safety NOC & Structural Stability Certificate', documentNumber: 'PMRDA/FIRE/NOC/2026/184', issueDate: '2026-02-14', expiryDate: '2027-02-13', issuingAuthority: 'PMRDA Fire Department', fileName: 'fire_safety_noc_pmrda.pdf', fileSizeMb: 2.3, status: 'Uploaded', isMandatory: false },
  ],

  // Step 19
  confirmAccurate: true,
  confirmAuthority: true,
  confirmGenuineDocs: true,
  agreeGovtVerification: true,
  agreeMaintainRecords: true,
  agreeReportOutcomes: true,
  agreeUpdateInfo: true,
  agreePrivacyData: true,
  agreeRevocationTerms: true,
  dataProcessingConsent: true,

  auditLogs: [
    {
      id: 'log-1',
      user: 'Suhas Kulkarni (MD)',
      role: 'Authorised Representative',
      action: 'Profile Initialized from Draft',
      timestamp: '16 Sep 2026, 11:25 AM',
      newValue: 'Comprehensive Data Populated',
      reason: 'Full application drafted for KAUSHAL state verification',
      ipAddress: '103.112.44.18 (Pune, Maharashtra)',
    },
    {
      id: 'log-2',
      user: 'Suhas Kulkarni (MD)',
      role: 'Authorised Representative',
      action: 'Added 3 Regional Training Centres',
      timestamp: '16 Sep 2026, 11:32 AM',
      newValue: 'Pune (Bhosari), Mumbai (Andheri), Nagpur (Hingna)',
      reason: 'Expanded centre capacity to 420 concurrent trainees',
      ipAddress: '103.112.44.18',
    },
    {
      id: 'log-3',
      user: 'Govt Verifier (DESD Desk-3)',
      role: 'District Skill Officer',
      action: 'Automated Pre-Check Validation Passed',
      timestamp: '16 Sep 2026, 11:38 AM',
      newValue: 'PAN & GSTIN Active (API Status 200)',
      reason: 'NSDL & GSTN instant verification check succeeded',
      ipAddress: '10.24.18.91 (MahaGov NKN Gateway)',
    },
  ],

  corrections: [
    {
      id: 'cor-1',
      field: 'Registered Office Address Proof',
      currentValue: 'registered_office_registered_lease.pdf',
      reviewerComment: 'Notarised lease copy verified; electricity bill attached is dated July 2026. Ready for final approval.',
      correctionType: 'document',
      status: 'Resolved',
    },
    {
      id: 'cor-2',
      field: 'Course 02: CNC Operator Syllabus',
      currentValue: 'cnc_operator_revised_nsqf4_90hrs.pdf',
      reviewerComment: 'Updated module breakdown now meets 90 practical hours standard. Verified by SSC Capital Goods.',
      correctionType: 'document',
      status: 'Resolved',
    },
  ],
};
